trigger:
- main


variables:
  dockerRegistryServiceConnection: 'afa00af4-25b6-41fb-9c46-3788df82d6d1'
  imageRepository: 'apiecommerceufsc'
  containerRegistry: 'ecommerceprojectufsc.azurecr.io'
  dockerfilePath: 'BE/Dockerfile'
  tag: '$(Build.BuildId)'
  
pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DownloadSecureFile@1
  displayName: Download appsettings.json
  name: appsettings
  inputs: 
    secureFile: 'appsettings.Production.json'

- script: |
    cp "$(appsettings.secureFilePath)" "BE/src/Backend/EcommerceProjectUFSC.API/appsettings.Production.json"


- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)
